compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

httpTimeout: 300000

nodeLinker: node-modules

packageExtensions:
  "@cowprotocol/widget-react@*":
    peerDependencies:
      "@types/react": ^19.0.0
      react: ^19.0.0
  "@storybook/core@*":
    dependencies:
      "@types/react": ^19.0.0
      react: ^19.0.0
  eslint-config-next@*:
    dependencies:
      next: "*"
  react-papaparse@*:
    peerDependencies:
      react: ^19.0.0
