name: Build docker image for darwinia

on:
  push:
    branches:
      - new-darwinia

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Sha
        uses: benjlevesque/short-sha@v3.0

      - name: Publish docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: apps/web/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:sha-${{ env.SHA }}
